openapi: 3.0.0
info:
  x-skaffolder-id-project: 5f5be85167541c707d17d242
  title: poc
  description: You can obtain JWT token from login API
  version: 0.1
servers:
  - url: http://localhost:3000/api
    description: Local server for testing
paths:
  /login:
    post:
      x-skaffolder-ignore: true
      summary: Login API
      security: []
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              example:
                username: admin
                password: 62f264d7ad826f02a8af714c0a54b197935b717656b80461686d450f7b3abde4c553541515de2052b9af70f710f0cd8a1a2d3f4d60aa72608d71a63a9a93c0f5
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /verifyToken:
    post:
      x-skaffolder-ignore: true
      summary: Verify token API
      security: []
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /changePassword:
    post:
      x-skaffolder-ignore: true
      summary: Change password API
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                passwordNew:
                  type: string
                passwordOld:
                  type: string
      responses:
        "200":
          description: OK
  /marketcontext:
    post:
      x-skaffolder-id: 5f62226067541c707d17dd2b
      x-skaffolder-name: create
      x-skaffolder-id-resource: 5f62225367541c707d17dd26
      x-skaffolder-resource: MarketContext
      x-skaffolder-crudAction: create
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION create
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION create
      tags:
        - MarketContext
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MarketContext"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Text:
                  type: string
    get:
      x-skaffolder-id: 5f62226067541c707d17dd2f
      x-skaffolder-name: list
      x-skaffolder-id-resource: 5f62225367541c707d17dd26
      x-skaffolder-resource: MarketContext
      x-skaffolder-crudAction: list
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION list
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION list
      tags:
        - MarketContext
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MarketContext"
  "/marketcontext/{id}":
    delete:
      x-skaffolder-id: 5f62226067541c707d17dd30
      x-skaffolder-name: delete
      x-skaffolder-id-resource: 5f62225367541c707d17dd26
      x-skaffolder-resource: MarketContext
      x-skaffolder-crudAction: delete
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION delete
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION delete
      tags:
        - MarketContext
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    get:
      x-skaffolder-id: 5f62226067541c707d17dd29
      x-skaffolder-name: get
      x-skaffolder-id-resource: 5f62225367541c707d17dd26
      x-skaffolder-resource: MarketContext
      x-skaffolder-crudAction: get
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION get
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION get
      tags:
        - MarketContext
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id resource
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MarketContext"
    post:
      x-skaffolder-id: 5f62226067541c707d17dd2a
      x-skaffolder-name: update
      x-skaffolder-id-resource: 5f62225367541c707d17dd26
      x-skaffolder-resource: MarketContext
      x-skaffolder-crudAction: update
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION update
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION update
      tags:
        - MarketContext
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MarketContext"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MarketContext"
  "/user/{id}/changePassword":
    post:
      x-skaffolder-id: 5f5be85167541c707d17d252
      x-skaffolder-name: changePassword
      x-skaffolder-id-resource: 5f5be85167541c707d17d24c
      x-skaffolder-resource: User
      x-skaffolder-crudAction: 
      x-skaffolder-crudType: 
      x-skaffolder-description: Change password of user from admin
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: object
      x-skaffolder-url: /{id}/changePassword
      x-skaffolder-roles:
        - 5f5be85167541c707d17d24e
      summary: Change password of user from admin
      tags:
        - User
      responses:
        "200":
          description: OK
  /user:
    post:
      x-skaffolder-id: 5f5be85167541c707d17d254
      x-skaffolder-name: create
      x-skaffolder-id-resource: 5f5be85167541c707d17d24c
      x-skaffolder-resource: User
      x-skaffolder-crudAction: create
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION create
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION create
      tags:
        - User
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mail:
                  type: string
                name:
                  type: string
                password:
                  type: string
                roles:
                  type: string
                surname:
                  type: string
                username:
                  type: string
    get:
      x-skaffolder-id: 5f5be85167541c707d17d24f
      x-skaffolder-name: list
      x-skaffolder-id-resource: 5f5be85167541c707d17d24c
      x-skaffolder-resource: User
      x-skaffolder-crudAction: list
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION list
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION list
      tags:
        - User
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
  "/user/{id}":
    delete:
      x-skaffolder-id: 5f5be85167541c707d17d250
      x-skaffolder-name: delete
      x-skaffolder-id-resource: 5f5be85167541c707d17d24c
      x-skaffolder-resource: User
      x-skaffolder-crudAction: delete
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION delete
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION delete
      tags:
        - User
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    get:
      x-skaffolder-id: 5f5be85167541c707d17d253
      x-skaffolder-name: get
      x-skaffolder-id-resource: 5f5be85167541c707d17d24c
      x-skaffolder-resource: User
      x-skaffolder-crudAction: get
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION get
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION get
      tags:
        - User
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id resource
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    post:
      x-skaffolder-id: 5f5be85167541c707d17d251
      x-skaffolder-name: update
      x-skaffolder-id-resource: 5f5be85167541c707d17d24c
      x-skaffolder-resource: User
      x-skaffolder-crudAction: update
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION update
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION update
      tags:
        - User
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    MarketContext:
      x-skaffolder-id: 5f62225367541c707d17dd26
      x-skaffolder-id-db: 5f5be85167541c707d17d243
      x-skaffolder-id-entity: 5f62225367541c707d17dd24
      x-skaffolder-url: /marketcontext
      properties:
        _id:
          type: string
          x-skaffolder-required: true
        Text:
          type: string
          x-skaffolder-id-attr: 5f62225367541c707d17dd25
          x-skaffolder-type: String
      x-skaffolder-relations: 
      required:
        - _id
    User:
      x-skaffolder-id: 5f5be85167541c707d17d24c
      x-skaffolder-id-db: 5f5be85167541c707d17d243
      x-skaffolder-id-entity: 5f5be85167541c707d17d244
      x-skaffolder-url: /user
      x-skaffolder-type: User
      properties:
        _id:
          type: string
          x-skaffolder-required: true
        mail:
          type: string
          x-skaffolder-id-attr: 5f5be85167541c707d17d247
          x-skaffolder-type: String
        name:
          type: string
          x-skaffolder-id-attr: 5f5be85167541c707d17d248
          x-skaffolder-type: String
        password:
          type: string
          x-skaffolder-id-attr: 5f5be85167541c707d17d246
          x-skaffolder-type: String
          x-skaffolder-required: true
        roles:
          type: string
          x-skaffolder-id-attr: 5f5be85167541c707d17d24a
          x-skaffolder-type: String
        surname:
          type: string
          x-skaffolder-id-attr: 5f5be85167541c707d17d249
          x-skaffolder-type: String
        username:
          type: string
          x-skaffolder-id-attr: 5f5be85167541c707d17d245
          x-skaffolder-type: String
          x-skaffolder-required: true
      x-skaffolder-relations: 
      required:
        - _id
        - password
        - username
  x-skaffolder-db:
    - x-skaffolder-id: 5f5be85167541c707d17d243
      x-skaffolder-name: gridf_db
  x-skaffolder-page:
    - x-skaffolder-id: 5f5be85167541c707d17d24b
      x-skaffolder-name: Home
      x-skaffolder-url: /home
      x-skaffolder-template: 
      x-skaffolder-resource: 
      x-skaffolder-services: 
      x-skaffolder-nesteds: 
      x-skaffolder-links:
        - 5f62226067541c707d17dd2e
      x-skaffolder-roles: []
    - x-skaffolder-id: 5f62226067541c707d17dd28
      x-skaffolder-name: MarketContextEdit
      x-skaffolder-url: /marketcontexts/{id}
      x-skaffolder-template: Edit_Crud
      x-skaffolder-resource: 5f62225367541c707d17dd26
      x-skaffolder-services:
        - 5f62226067541c707d17dd2b
        - 5f62226067541c707d17dd2a
        - 5f62226067541c707d17dd29
      x-skaffolder-nesteds: 
      x-skaffolder-links: 
      x-skaffolder-roles: []
    - x-skaffolder-id: 5f62226067541c707d17dd2e
      x-skaffolder-name: MarketContextList
      x-skaffolder-url: /marketcontexts
      x-skaffolder-template: List_Crud
      x-skaffolder-resource: 5f62225367541c707d17dd26
      x-skaffolder-services:
        - 5f62226067541c707d17dd30
        - 5f62226067541c707d17dd2f
      x-skaffolder-nesteds: 
      x-skaffolder-links:
        - 5f62226067541c707d17dd28
      x-skaffolder-roles: []
  x-skaffolder-roles: 
    - x-skaffolder-id: 5f5be85167541c707d17d24e
      x-skaffolder-name: ADMIN
